# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Title Armadillo package matrix inversion function
#' Description Takes a matrix and inverts it.
#' @param x matrix to be inverted
#' @return Inverted matrix
#' @noRd
rcpparma_armaInv <- function(x) {
    .Call(`_baselineARPLss_rcpparma_armaInv`, x)
}

